server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xueke_springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver # ????????????????
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true  # ???????
      additional-paths: src/main/java # ????
      exclude: WEB-INF/**
  freemarker:
    cache: false    # ??????????????
  redis:
    host: localhost
    port: 6379
    # 如果Redis设置了密码，请取消下面这行的注释并设置密码
    # password: your_password
    # 连接超时时间（毫秒）
    timeout: 10000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

logging:
  level:
    com.wms: debug